M1_SLIDES = [
    {"type": "content", "title": "Programme de la formation", "bullets": [
        "Module 1 - Gestion de projet Agile : Scrum & Kanban (3 jours / 21 h)",
        "Module 2 - Culture & outils DevOps : CI/CD, Docker, Kubernetes (4 jours / 28 h)",
        "Module 3 - Spring Security : JWT, OAuth2, Keycloak (5 jours / 35 h)",
        ("Fil rouge : application QuickBite (commande de repas en ligne)", 1),
        ("Pedagogie : 30 % theorie + 70 % ateliers pratiques + corrige commente", 1),
    ]},
    {"type": "section", "title": "Module 1 - Agilite", "subtitle": "Scrum & Kanban | Roles PO / Scrum Master | 3 jours"},
    {"type": "content", "title": "Pourquoi l'Agilite ? Le probleme de depart", "bullets": [
        "Avant 2000 : cycle cascade - specifier tout, livrer 12-18 mois plus tard",
        "Etude Standish CHAOS : 66 % des projets hors budget ou delai",
        "45 % des fonctionnalites livrees ne sont jamais utilisees",
        "Le cout du changement explose en fin de cycle (x100 vs debut)",
        ("Solution : raccourcir la boucle idee -> validation utilisateur", 1),
    ]},
    {"type": "content", "title": "Naissance du Manifeste Agile (2001)", "bullets": [
        "17 praticiens a Snowbird (Utah) : Beck, Fowler, Schwaber, Sutherland...",
        "Origines : XP (1999), Scrum (1995), Crystal, DSDM, Lean",
        "1986 : Takeuchi & Nonaka - metaphore du rugby (scrum) en developpement",
        "Agile = etat d'esprit (mindset), pas une methode ni un outil",
        ("Declinaisons : Scrum, Kanban, XP, SAFe, LeSS, Disciplined Agile", 1),
    ]},
    {"type": "content", "title": "Le Manifeste Agile - 4 valeurs", "bullets": [
        "Individus & interactions  >  processus et outils",
        "Logiciel qui fonctionne  >  documentation exhaustive",
        "Collaboration avec le client  >  negociation contractuelle",
        "Adaptation au changement  >  suivi d'un plan",
        ("Important : les elements de droite ont de la valeur - on deplace le curseur", 1),
    ]},
    {"type": "content", "title": "Les 12 principes - 4 familles", "bullets": [
        "A. Valeur client : livrer tot et souvent, accueillir le changement meme tardif",
        "B. Collaboration : travail quotidien metier<->devs, confiance, face-a-face",
        "C. Mesure : logiciel qui fonctionne = seule mesure d'avancement reel",
        "D. Excellence : rythme soutenable, qualite technique, equipes auto-organisees",
        ("Principe 12 : retro reguliere - l'equipe ajuste son comportement", 1),
    ]},
    {"type": "content", "title": "Predictif vs Adaptatif", "bullets": [
        "Cycle en V : besoin stable, valeur a la fin, changement = avenant couteux",
        "Agile : besoin evolutif, valeur a chaque iteration, changement = bienvenu",
        "Iteratif : on repasse pour ameliorer | Incremental : on ajoute des morceaux",
        "Agile combine les deux : skateboard->trottinette->velo->voiture (pas roue seule)",
        ("Cycle en V pertinent : logiciel embarque certifie, domaine reglementaire stable", 1),
    ]},
    {"type": "content", "title": "Concepts cles - MVP & Feedback", "bullets": [
        "MVP (Minimum Viable Product) : plus petite version permettant d'APPRENDRE",
        "Bon MVP QuickBite : commander 1 plat dans 1 resto + payer (bout-en-bout)",
        "Valeur metier : priorite par valeur pour l'utilisateur, pas par facilite technique",
        "Boucle feedback : Construire -> Mesurer -> Apprendre -> (recommencer)",
        ("Plus la boucle est courte, plus on corrige tot et moins cher", 1),
    ]},
    {"type": "content", "title": "Definition of Ready & Definition of Done", "bullets": [
        "DoR (pret) : story claire, estimee, criteres d'acceptation definis, dependances connues",
        "DoD (termine) : code revu, teste, integre, deploye, documente, demonstre",
        "Sans DoD : le 'presque fini' s'accumule et detruit la predictibilite",
        "DoD est une checklist partagee et NON NEGOCIABLE par item de backlog",
        ("Astuce : afficher la DoD sur le mur de l'equipe, visible de tous", 1),
    ]},
    {"type": "content", "title": "Scrum - Fondations & 5 valeurs", "bullets": [
        "Cadre empirique leger : transparence (tout le monde voit la realite), inspection, adaptation",
        "5 valeurs : Engagement - Focus - Ouverture - Respect - Courage",
        "Engagement : sur l'objectif du sprint, pas sur une liste de taches figee",
        "Courage : dire la verite, signaler les obstacles, remettre en question les decisions",
        ("Sprint = iteration de duree fixe 1-4 semaines, enchainees sans interruption", 1),
    ]},
    {"type": "content", "title": "Scrum - Les 3 roles", "bullets": [
        "Product Owner : QUOI & POURQUOI - possede et ordonne le Product Backlog",
        "Outils PO : story mapping, MoSCoW, WSJF, roadmap, criteres d'acceptation",
        "Scrum Master : leader serviteur - facilite, leve obstacles, coache, protege",
        "SM ≠ chef de projet : influence et coaching, zero autorite hierarchique",
        ("Developpeurs : auto-organises, pluridisciplinaires - decidient du COMMENT", 1),
    ]},
    {"type": "content", "title": "Story Mapping - Outil cle du PO", "bullets": [
        "Axe horizontal : parcours utilisateur (activites -> taches utilisateur)",
        "Axe vertical : priorites en tranches (release 1, release 2, backlog)",
        "Permet de definir le MVP : 1ere tranche = valeur minimum bout-en-bout",
        "Exemple QuickBite : S'inscrire | Chercher | Commander | Payer | Suivre",
        ("Revele les dependances et trous avant de commencer a developper", 1),
    ]},
    {"type": "content", "title": "Scrum - Artefacts & Engagements", "bullets": [
        "Product Backlog + Product Goal : liste ordonnee de tout ce qui pourrait etre fait",
        "Sprint Backlog + Sprint Goal : selection du sprint + plan de realisation",
        "Increment + DoD : somme des items 'Done', utilisable, potentiellement livrable",
        "Sprint Goal donne la coherence - on peut changer les items SI le goal est atteint",
        ("Scrum 2020 : chaque artefact a un engagement qui mesure le progres", 1),
    ]},
    {"type": "content", "title": "Scrum - Les 5 evenements", "bullets": [
        "Sprint (1-4 sem) : conteneur de tous les autres evenements",
        "Sprint Planning (<=4h pour 2 sem) : Pourquoi ? Quoi ? Comment ?",
        "Daily Scrum (15 min) : synchro entre devs devant le board, pas un reporting",
        "Sprint Review (<=2h) : inspecter le PRODUIT avec les parties prenantes",
        ("Sprint Retrospective (<=1h30) : inspecter le PROCESSUS - Start/Stop/Continue", 1),
    ]},
    {"type": "content", "title": "User Stories & Estimation", "bullets": [
        "Hierarchie : Epic -> User Story (1 sprint) -> Task (quelques heures)",
        "Format : En tant que [role], je veux [action] afin de [benefice]",
        "INVEST : Independent, Negotiable, Valuable, Estimable, Small, Testable",
        "Planning Poker : points Fibonacci (1,2,3,5,8,13,21) - revelation simultanee",
        ("MoSCoW : Must have / Should have / Could have / Won't have (now)", 1),
    ]},
    {"type": "content", "title": "Kanban - Principes & Pratiques", "bullets": [
        "Origine : Toyota Production System (juste-a-temps) - applique au logiciel en 2010",
        "1. Visualiser le travail | 2. Limiter le WIP | 3. Gerer le flux",
        "4. Rendre les regles explicites | 5. Boucles de feedback | 6. S'ameliorer",
        "WIP (Work In Progress) : nombre d'items en cours - limiter = terminer avant de commencer",
        ("Loi de Little : Lead time = WIP / Throughput - reduire WIP reduit les delais", 1),
    ]},
    {"type": "content", "title": "Kanban - Metriques & CFD", "bullets": [
        "Lead time : du moment de la demande a la livraison (vu du CLIENT)",
        "Cycle time : du debut du travail a la livraison (vu de l'EQUIPE)",
        "Throughput : nombre d'items termines par unite de temps (capacite reelle)",
        "CFD (Cumulative Flow Diagram) : bande s'elargissant = goulot visible",
        ("Classes de service : Standard | Urgent (WIP=1) | Date fixe | Intangible", 1),
    ]},
    {"type": "content", "title": "Scrum vs Kanban vs ScrumBan", "bullets": [
        "Scrum : iterations fixes, Sprint Goal, 3 roles imposes -> developpement produit",
        "Kanban : flux continu, WIP par colonne, aucun role impose -> support/ops",
        "ScrumBan : hybride - equipe Scrum noyee par les urgences ou en transition",
        "Choisir selon : type de travail previsible ? horizon planifiable ? urgences frequentes ?",
        ("Pas de meilleur cadre - le contexte dicte le choix", 1),
    ]},
    {"type": "content", "title": "Outils de gestion Agile", "bullets": [
        "Jira : puissant, reporting avance, epics/sprints, Agile a l'echelle",
        "Trello : visuel, simple, prise en main < 1h, Kanban leger",
        "ClickUp : polyvalent - docs, objectifs, vues Gantt/board/liste",
        "GitHub Projects : couple au code, issues, PR, automatisation native",
        ("Asana : taches, echeances, coordination inter-equipes", 1),
    ]},
    {"type": "content", "title": "Module 1 - Ateliers (recap)", "bullets": [
        "Atelier 1 (J1, 1h30) : Diagnostiquer FidExpress - 5 pourquoi -> transition Agile",
        "Atelier 2 (J2, 2h) : Product Backlog QuickBite + Planning Poker + Sprint 1",
        "Atelier 3 (J3, 1h30) : Tableau Kanban + simulation 5 jours + goulot -> fix",
        "Mini-atelier outil : board QuickBite sur Trello ou GitHub Projects",
        ("Evaluation finale : QCM 10 pts + etude de cas equipe support (10 pts)", 1),
    ]},
]
print("M1 OK:", len(M1_SLIDES), "slides")
